services:
  school_ctfd:
    image: ctfd/ctfd:3.5.0
    user: root
    restart: always
    expose:
      - "8000"
    env_file:
      - .school.env
    volumes:
      - school_ctfd_logs:/var/log/CTFd
      - school_ctfd_uploads:/var/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.school.rule=Host(`yetictf.nstu.ru`) && PathPrefix(`/school`)"
      - "traefik.http.routers.school.entrypoints=websecure"
      - "traefik.http.routers.school.tls.certresolver=lets-encr"
    depends_on:
      - school_db
    networks:
      default:
      web:

  school_db:
    image: mariadb:10.4.12
    restart: always
    env_file:
      - .school.env
    volumes:
      - school_mysql_data:/var/lib/mysql
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  school_db_backup:
    image: tiredofit/db-backup
    restart: always
    depends_on:
      - school_db
      - school_ctfd
    env_file:
      - .school.env

  school_cache:
    image: redis:4
    restart: always
    volumes:
      - school_redis_data:/data

volumes:
  school_mysql_data:
  school_redis_data:
  school_ctfd_logs:
  school_ctfd_uploads:

networks:
  web:
  default:
